//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURING_SETUP
    {
        public string POT { get; set; }
        public Nullable<decimal> DEPARTMENT { get; set; }
        public string GREEN_TIRE_NUMBER { get; set; }
        public Nullable<decimal> TOTAL_CYCLE_TIME { get; set; }
        public string MOLD { get; set; }
        public string CURE_NUMBER { get; set; }
        public string SKU { get; set; }
    }
}
