//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEFECT_EXPORT
    {
        public decimal ROW_SEQ { get; set; }
        public string GRADE_TYPE_CODE { get; set; }
        public string GRADE_DISPOSITION { get; set; }
        public string INSPECTOR_BADGE { get; set; }
        public string BUILD_BADGE_2 { get; set; }
        public string COMMENTS { get; set; }
        public string BUILD_MACHINE_2 { get; set; }
        public Nullable<System.DateTime> GRADE_ENTRY_DATE { get; set; }
        public Nullable<System.DateTime> GRADE_ENTRY_TIME { get; set; }
        public string SKU { get; set; }
        public string MOLD { get; set; }
        public string SHIFT { get; set; }
        public Nullable<decimal> LOT { get; set; }
        public string BUILD_MACHINE { get; set; }
        public string BUILDER_BADGE { get; set; }
        public string POT { get; set; }
        public string TIRE_SERIAL { get; set; }
    }
}
