//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELAY_CODES
    {
        public decimal ID { get; set; }
        public Nullable<decimal> DEPARTMENT { get; set; }
        public string AREA { get; set; }
        public Nullable<decimal> DELAY_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string COMMENT_REQUIRED { get; set; }
        public string MUD { get; set; }
    }
}
