//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentLog
    {
        public decimal Id { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string EventName { get; set; }
        public string MachineName { get; set; }
        public string PartSerialNumber { get; set; }
        public string OperatorSerialNumber { get; set; }
        public string DataName1 { get; set; }
        public string DataValue1 { get; set; }
        public string DataName2 { get; set; }
        public string DataValue2 { get; set; }
        public string DataName3 { get; set; }
        public string DataValue3 { get; set; }
        public string DataName4 { get; set; }
        public string DataValue4 { get; set; }
        public string DataName5 { get; set; }
        public string DataValue5 { get; set; }
        public string DataName6 { get; set; }
        public string DataValue6 { get; set; }
        public string DataName7 { get; set; }
        public string DataValue7 { get; set; }
        public string DataName8 { get; set; }
        public string DataValue8 { get; set; }
        public string DataName9 { get; set; }
        public string DataValue9 { get; set; }
        public string DataName10 { get; set; }
        public string DataValue10 { get; set; }
        public string DataName11 { get; set; }
        public string DataValue11 { get; set; }
        public string DataName12 { get; set; }
        public string DataValue12 { get; set; }
        public string DataName13 { get; set; }
        public string DataValue13 { get; set; }
        public string DataName14 { get; set; }
        public string DataValue14 { get; set; }
        public string DataName15 { get; set; }
        public string DataValue15 { get; set; }
        public string DataName16 { get; set; }
        public string DataValue16 { get; set; }
        public string DataName17 { get; set; }
        public string DataValue17 { get; set; }
        public string DataName18 { get; set; }
        public string DataValue18 { get; set; }
        public string DataName19 { get; set; }
        public string DataValue19 { get; set; }
        public string DataName20 { get; set; }
        public string DataValue20 { get; set; }
    }
}
