//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT_LOG
    {
        public decimal DEPARTMENT_LOG_ID { get; set; }
        public System.DateTime CREATED { get; set; }
        public string EVENT_NAME { get; set; }
        public string MACHINE_NAME { get; set; }
        public string PART_SERIAL_NUMBER { get; set; }
        public string OPERATOR_SERIAL_NUMBER { get; set; }
        public string DATA_NAME_1 { get; set; }
        public string DATA_VALUE_1 { get; set; }
        public string DATA_NAME_2 { get; set; }
        public string DATA_VALUE_2 { get; set; }
        public string DATA_NAME_3 { get; set; }
        public string DATA_VALUE_3 { get; set; }
        public string DATA_NAME_4 { get; set; }
        public string DATA_VALUE_4 { get; set; }
        public string DATA_NAME_5 { get; set; }
        public string DATA_VALUE_5 { get; set; }
        public string DATA_NAME_6 { get; set; }
        public string DATA_VALUE_6 { get; set; }
        public string DATA_NAME_7 { get; set; }
        public string DATA_VALUE_7 { get; set; }
        public string DATA_NAME_8 { get; set; }
        public string DATA_VALUE_8 { get; set; }
        public string DATA_NAME_9 { get; set; }
        public string DATA_VALUE_9 { get; set; }
        public string DATA_NAME_10 { get; set; }
        public string DATA_VALUE_10 { get; set; }
        public string DATA_NAME_11 { get; set; }
        public string DATA_VALUE_11 { get; set; }
        public string DATA_NAME_12 { get; set; }
        public string DATA_VALUE_12 { get; set; }
        public string DATA_NAME_13 { get; set; }
        public string DATA_VALUE_13 { get; set; }
        public string DATA_NAME_14 { get; set; }
        public string DATA_VALUE_14 { get; set; }
        public string DATA_NAME_15 { get; set; }
        public string DATA_VALUE_15 { get; set; }
        public string DATA_NAME_16 { get; set; }
        public string DATA_VALUE_16 { get; set; }
        public string DATA_NAME_17 { get; set; }
        public string DATA_VALUE_17 { get; set; }
        public string DATA_NAME_18 { get; set; }
        public string DATA_VALUE_18 { get; set; }
        public string DATA_NAME_19 { get; set; }
        public string DATA_VALUE_19 { get; set; }
        public string DATA_NAME_20 { get; set; }
        public string DATA_VALUE_20 { get; set; }
    }
}
