//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CURING_SETUP> CURING_SETUP { get; set; }
        public DbSet<DEFECT_EXPORT> DEFECT_EXPORT { get; set; }
        public DbSet<DELAY_CODES> DELAY_CODES { get; set; }
        public DbSet<DEPARTMENT> DEPARTMENTs { get; set; }
        public DbSet<DepartmentLog> DepartmentLogs { get; set; }
        public DbSet<EVENT> EVENTs { get; set; }
        public DbSet<EVENT_CARD_LOG> EVENT_CARD_LOG { get; set; }
        public DbSet<EVENT_DATA> EVENT_DATA { get; set; }
        public DbSet<EVENT_LOG> EVENT_LOG { get; set; }
        public DbSet<EVENT_LOG_DATA> EVENT_LOG_DATA { get; set; }
        public DbSet<EVENT_LOG_SHIFT> EVENT_LOG_SHIFT { get; set; }
        public DbSet<GOODTIRE_LOG> GOODTIRE_LOG { get; set; }
        public DbSet<GreenTire> GreenTires { get; set; }
        public DbSet<GTI_EXPORT_BUILT> GTI_EXPORT_BUILT { get; set; }
        public DbSet<GTI_EXPORT_CURED> GTI_EXPORT_CURED { get; set; }
        public DbSet<MACHINE> MACHINEs { get; set; }
        public DbSet<MESSAGE> MESSAGEs { get; set; }
        public DbSet<NOTIFICATION_LOG> NOTIFICATION_LOG { get; set; }
        public DbSet<OPERATOR> OPERATORs { get; set; }
        public DbSet<OPERATOR_IMPORT> OPERATOR_IMPORT { get; set; }
        public DbSet<OPERATOR_IMPORT2> OPERATOR_IMPORT2 { get; set; }
        public DbSet<OPERATOR_RECONCILE> OPERATOR_RECONCILE { get; set; }
        public DbSet<Part> Parts { get; set; }
        public DbSet<SHIFT> SHIFTs { get; set; }
        public DbSet<SHIFT_DEFINITION> SHIFT_DEFINITION { get; set; }
        public DbSet<TESTINSERTEVENTLOG> TESTINSERTEVENTLOGs { get; set; }
        public DbSet<UPH_STANDARDS> UPH_STANDARDS { get; set; }
        public DbSet<CURING_PIVOT_VIEW> CURING_PIVOT_VIEW { get; set; }
        public DbSet<CURRENT_SHIFT_VIEW> CURRENT_SHIFT_VIEW { get; set; }
        public DbSet<DOWNTIME_ORPHANS> DOWNTIME_ORPHANS { get; set; }
        public DbSet<EVENT_CARD_LOG_VIEW> EVENT_CARD_LOG_VIEW { get; set; }
        public DbSet<EVENT_COUNT_VIEW> EVENT_COUNT_VIEW { get; set; }
        public DbSet<EVENT_DATA_COUNT_VIEW> EVENT_DATA_COUNT_VIEW { get; set; }
        public DbSet<EVENT_LAST_GOODTIRE_SEC_NEW> EVENT_LAST_GOODTIRE_SEC_NEW { get; set; }
        public DbSet<EVENT_LAST_GOODTIRE_SECONDS> EVENT_LAST_GOODTIRE_SECONDS { get; set; }
        public DbSet<EVENT_LOG_VIEW> EVENT_LOG_VIEW { get; set; }
        public DbSet<EVENT_LOG_VIEW_WITH_SHIFT> EVENT_LOG_VIEW_WITH_SHIFT { get; set; }
        public DbSet<EVENT_LOG_VIEW_WITH_SHIFT_NEW> EVENT_LOG_VIEW_WITH_SHIFT_NEW { get; set; }
        public DbSet<FINISHING_PIVOT_VIEW> FINISHING_PIVOT_VIEW { get; set; }
        public DbSet<GTI_BUILT_VIEW> GTI_BUILT_VIEW { get; set; }
        public DbSet<GTI_COUNT_VIEW> GTI_COUNT_VIEW { get; set; }
        public DbSet<GTI_CURED_VIEW> GTI_CURED_VIEW { get; set; }
        public DbSet<MACHINE_COUNT_VIEW> MACHINE_COUNT_VIEW { get; set; }
        public DbSet<MACHINE_EVENT_COUNT_LAST_Day> MACHINE_EVENT_COUNT_LAST_Day { get; set; }
        public DbSet<MACHINE_GOOD_TIRE_COUNT_VIEW> MACHINE_GOOD_TIRE_COUNT_VIEW { get; set; }
        public DbSet<MACHINE_GOOD_TIRE_VIEW> MACHINE_GOOD_TIRE_VIEW { get; set; }
        public DbSet<MACHINE_GOOD_TIRE_VIEW_NEW> MACHINE_GOOD_TIRE_VIEW_NEW { get; set; }
        public DbSet<MACHINE_PART_VIEW> MACHINE_PART_VIEW { get; set; }
        public DbSet<MACHINE_PART_VIEW_NEW> MACHINE_PART_VIEW_NEW { get; set; }
        public DbSet<MACHINE_SCAN_SCORE> MACHINE_SCAN_SCORE { get; set; }
        public DbSet<OPERATOR_GOOD_TIRE_COUNT_VIEW> OPERATOR_GOOD_TIRE_COUNT_VIEW { get; set; }
        public DbSet<OPERATOR_GOOD_TIRE_VIEW> OPERATOR_GOOD_TIRE_VIEW { get; set; }
        public DbSet<OPERATOR_GOOD_TIRE_VIEW_NEW> OPERATOR_GOOD_TIRE_VIEW_NEW { get; set; }
        public DbSet<OPERATOR_PART_VIEW> OPERATOR_PART_VIEW { get; set; }
        public DbSet<OPERATOR_PART_VIEW_NEW> OPERATOR_PART_VIEW_NEW { get; set; }
        public DbSet<OPERATOR_PARTS_BUILD_FINISH> OPERATOR_PARTS_BUILD_FINISH { get; set; }
        public DbSet<PART_BUILD_CURE_VIEW> PART_BUILD_CURE_VIEW { get; set; }
        public DbSet<PART_EVENT_VIEW> PART_EVENT_VIEW { get; set; }
        public DbSet<SAP_NOTIFICATION_LOG> SAP_NOTIFICATION_LOG { get; set; }
        public DbSet<SHIFT_VIEW> SHIFT_VIEW { get; set; }
    
        public virtual int HANDLE_CURE_TIRE_LOG(Nullable<decimal> p_EVENT_LOG_ID, string p_PART_SERIAL, string p_POT)
        {
            var p_EVENT_LOG_IDParameter = p_EVENT_LOG_ID.HasValue ?
                new ObjectParameter("P_EVENT_LOG_ID", p_EVENT_LOG_ID) :
                new ObjectParameter("P_EVENT_LOG_ID", typeof(decimal));
    
            var p_PART_SERIALParameter = p_PART_SERIAL != null ?
                new ObjectParameter("P_PART_SERIAL", p_PART_SERIAL) :
                new ObjectParameter("P_PART_SERIAL", typeof(string));
    
            var p_POTParameter = p_POT != null ?
                new ObjectParameter("P_POT", p_POT) :
                new ObjectParameter("P_POT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HANDLE_CURE_TIRE_LOG", p_EVENT_LOG_IDParameter, p_PART_SERIALParameter, p_POTParameter);
        }
    
        public virtual int INSERT_DEFECT_EXPORT(string p_EVENT_LOG_ID)
        {
            var p_EVENT_LOG_IDParameter = p_EVENT_LOG_ID != null ?
                new ObjectParameter("P_EVENT_LOG_ID", p_EVENT_LOG_ID) :
                new ObjectParameter("P_EVENT_LOG_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_DEFECT_EXPORT", p_EVENT_LOG_IDParameter);
        }
    
        public virtual int INSERT_EVENT_CARD_LOG(string p_EVENT_NAME, string p_OPERATOR_SERIAL, string p_MACHINE, string p_PART_NUMBER, string p_DATA_VALUE1, string p_DATA_VALUE2, string p_DATA_VALUE3, string p_DATA_VALUE4, string p_DATA_VALUE5, string p_DATA_NAME1)
        {
            var p_EVENT_NAMEParameter = p_EVENT_NAME != null ?
                new ObjectParameter("P_EVENT_NAME", p_EVENT_NAME) :
                new ObjectParameter("P_EVENT_NAME", typeof(string));
    
            var p_OPERATOR_SERIALParameter = p_OPERATOR_SERIAL != null ?
                new ObjectParameter("P_OPERATOR_SERIAL", p_OPERATOR_SERIAL) :
                new ObjectParameter("P_OPERATOR_SERIAL", typeof(string));
    
            var p_MACHINEParameter = p_MACHINE != null ?
                new ObjectParameter("P_MACHINE", p_MACHINE) :
                new ObjectParameter("P_MACHINE", typeof(string));
    
            var p_PART_NUMBERParameter = p_PART_NUMBER != null ?
                new ObjectParameter("P_PART_NUMBER", p_PART_NUMBER) :
                new ObjectParameter("P_PART_NUMBER", typeof(string));
    
            var p_DATA_VALUE1Parameter = p_DATA_VALUE1 != null ?
                new ObjectParameter("P_DATA_VALUE1", p_DATA_VALUE1) :
                new ObjectParameter("P_DATA_VALUE1", typeof(string));
    
            var p_DATA_VALUE2Parameter = p_DATA_VALUE2 != null ?
                new ObjectParameter("P_DATA_VALUE2", p_DATA_VALUE2) :
                new ObjectParameter("P_DATA_VALUE2", typeof(string));
    
            var p_DATA_VALUE3Parameter = p_DATA_VALUE3 != null ?
                new ObjectParameter("P_DATA_VALUE3", p_DATA_VALUE3) :
                new ObjectParameter("P_DATA_VALUE3", typeof(string));
    
            var p_DATA_VALUE4Parameter = p_DATA_VALUE4 != null ?
                new ObjectParameter("P_DATA_VALUE4", p_DATA_VALUE4) :
                new ObjectParameter("P_DATA_VALUE4", typeof(string));
    
            var p_DATA_VALUE5Parameter = p_DATA_VALUE5 != null ?
                new ObjectParameter("P_DATA_VALUE5", p_DATA_VALUE5) :
                new ObjectParameter("P_DATA_VALUE5", typeof(string));
    
            var p_DATA_NAME1Parameter = p_DATA_NAME1 != null ?
                new ObjectParameter("P_DATA_NAME1", p_DATA_NAME1) :
                new ObjectParameter("P_DATA_NAME1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_EVENT_CARD_LOG", p_EVENT_NAMEParameter, p_OPERATOR_SERIALParameter, p_MACHINEParameter, p_PART_NUMBERParameter, p_DATA_VALUE1Parameter, p_DATA_VALUE2Parameter, p_DATA_VALUE3Parameter, p_DATA_VALUE4Parameter, p_DATA_VALUE5Parameter, p_DATA_NAME1Parameter);
        }
    
        public virtual int INSERT_EVENT_LOG(string eVENT_NAME, string mACHINE_NAME, string pART_SERIAL_NUMBER, string oPERATOR_SERIAL_NUMBER, string dATA_NAME_1, string dATA_VALUE_1, string dATA_NAME_2, string dATA_VALUE_2, string dATA_NAME_3, string dATA_VALUE_3, string dATA_NAME_4, string dATA_VALUE_4, string dATA_NAME_5, string dATA_VALUE_5, string dATA_NAME_6, string dATA_VALUE_6, string dATA_NAME_7, string dATA_VALUE_7, string dATA_NAME_8, string dATA_VALUE_8, string dATA_NAME_9, string dATA_VALUE_9, string dATA_NAME_10, string dATA_VALUE_10, string dATA_NAME_11, string dATA_VALUE_11, string dATA_NAME_12, string dATA_VALUE_12, string dATA_NAME_13, string dATA_VALUE_13, string dATA_NAME_14, string dATA_VALUE_14, string dATA_NAME_15, string dATA_VALUE_15, string dATA_NAME_16, string dATA_VALUE_16, string dATA_NAME_17, string dATA_VALUE_17, string dATA_NAME_18, string dATA_VALUE_18, string dATA_NAME_19, string dATA_VALUE_19, string dATA_NAME_20, string dATA_VALUE_20)
        {
            var eVENT_NAMEParameter = eVENT_NAME != null ?
                new ObjectParameter("EVENT_NAME", eVENT_NAME) :
                new ObjectParameter("EVENT_NAME", typeof(string));
    
            var mACHINE_NAMEParameter = mACHINE_NAME != null ?
                new ObjectParameter("MACHINE_NAME", mACHINE_NAME) :
                new ObjectParameter("MACHINE_NAME", typeof(string));
    
            var pART_SERIAL_NUMBERParameter = pART_SERIAL_NUMBER != null ?
                new ObjectParameter("PART_SERIAL_NUMBER", pART_SERIAL_NUMBER) :
                new ObjectParameter("PART_SERIAL_NUMBER", typeof(string));
    
            var oPERATOR_SERIAL_NUMBERParameter = oPERATOR_SERIAL_NUMBER != null ?
                new ObjectParameter("OPERATOR_SERIAL_NUMBER", oPERATOR_SERIAL_NUMBER) :
                new ObjectParameter("OPERATOR_SERIAL_NUMBER", typeof(string));
    
            var dATA_NAME_1Parameter = dATA_NAME_1 != null ?
                new ObjectParameter("DATA_NAME_1", dATA_NAME_1) :
                new ObjectParameter("DATA_NAME_1", typeof(string));
    
            var dATA_VALUE_1Parameter = dATA_VALUE_1 != null ?
                new ObjectParameter("DATA_VALUE_1", dATA_VALUE_1) :
                new ObjectParameter("DATA_VALUE_1", typeof(string));
    
            var dATA_NAME_2Parameter = dATA_NAME_2 != null ?
                new ObjectParameter("DATA_NAME_2", dATA_NAME_2) :
                new ObjectParameter("DATA_NAME_2", typeof(string));
    
            var dATA_VALUE_2Parameter = dATA_VALUE_2 != null ?
                new ObjectParameter("DATA_VALUE_2", dATA_VALUE_2) :
                new ObjectParameter("DATA_VALUE_2", typeof(string));
    
            var dATA_NAME_3Parameter = dATA_NAME_3 != null ?
                new ObjectParameter("DATA_NAME_3", dATA_NAME_3) :
                new ObjectParameter("DATA_NAME_3", typeof(string));
    
            var dATA_VALUE_3Parameter = dATA_VALUE_3 != null ?
                new ObjectParameter("DATA_VALUE_3", dATA_VALUE_3) :
                new ObjectParameter("DATA_VALUE_3", typeof(string));
    
            var dATA_NAME_4Parameter = dATA_NAME_4 != null ?
                new ObjectParameter("DATA_NAME_4", dATA_NAME_4) :
                new ObjectParameter("DATA_NAME_4", typeof(string));
    
            var dATA_VALUE_4Parameter = dATA_VALUE_4 != null ?
                new ObjectParameter("DATA_VALUE_4", dATA_VALUE_4) :
                new ObjectParameter("DATA_VALUE_4", typeof(string));
    
            var dATA_NAME_5Parameter = dATA_NAME_5 != null ?
                new ObjectParameter("DATA_NAME_5", dATA_NAME_5) :
                new ObjectParameter("DATA_NAME_5", typeof(string));
    
            var dATA_VALUE_5Parameter = dATA_VALUE_5 != null ?
                new ObjectParameter("DATA_VALUE_5", dATA_VALUE_5) :
                new ObjectParameter("DATA_VALUE_5", typeof(string));
    
            var dATA_NAME_6Parameter = dATA_NAME_6 != null ?
                new ObjectParameter("DATA_NAME_6", dATA_NAME_6) :
                new ObjectParameter("DATA_NAME_6", typeof(string));
    
            var dATA_VALUE_6Parameter = dATA_VALUE_6 != null ?
                new ObjectParameter("DATA_VALUE_6", dATA_VALUE_6) :
                new ObjectParameter("DATA_VALUE_6", typeof(string));
    
            var dATA_NAME_7Parameter = dATA_NAME_7 != null ?
                new ObjectParameter("DATA_NAME_7", dATA_NAME_7) :
                new ObjectParameter("DATA_NAME_7", typeof(string));
    
            var dATA_VALUE_7Parameter = dATA_VALUE_7 != null ?
                new ObjectParameter("DATA_VALUE_7", dATA_VALUE_7) :
                new ObjectParameter("DATA_VALUE_7", typeof(string));
    
            var dATA_NAME_8Parameter = dATA_NAME_8 != null ?
                new ObjectParameter("DATA_NAME_8", dATA_NAME_8) :
                new ObjectParameter("DATA_NAME_8", typeof(string));
    
            var dATA_VALUE_8Parameter = dATA_VALUE_8 != null ?
                new ObjectParameter("DATA_VALUE_8", dATA_VALUE_8) :
                new ObjectParameter("DATA_VALUE_8", typeof(string));
    
            var dATA_NAME_9Parameter = dATA_NAME_9 != null ?
                new ObjectParameter("DATA_NAME_9", dATA_NAME_9) :
                new ObjectParameter("DATA_NAME_9", typeof(string));
    
            var dATA_VALUE_9Parameter = dATA_VALUE_9 != null ?
                new ObjectParameter("DATA_VALUE_9", dATA_VALUE_9) :
                new ObjectParameter("DATA_VALUE_9", typeof(string));
    
            var dATA_NAME_10Parameter = dATA_NAME_10 != null ?
                new ObjectParameter("DATA_NAME_10", dATA_NAME_10) :
                new ObjectParameter("DATA_NAME_10", typeof(string));
    
            var dATA_VALUE_10Parameter = dATA_VALUE_10 != null ?
                new ObjectParameter("DATA_VALUE_10", dATA_VALUE_10) :
                new ObjectParameter("DATA_VALUE_10", typeof(string));
    
            var dATA_NAME_11Parameter = dATA_NAME_11 != null ?
                new ObjectParameter("DATA_NAME_11", dATA_NAME_11) :
                new ObjectParameter("DATA_NAME_11", typeof(string));
    
            var dATA_VALUE_11Parameter = dATA_VALUE_11 != null ?
                new ObjectParameter("DATA_VALUE_11", dATA_VALUE_11) :
                new ObjectParameter("DATA_VALUE_11", typeof(string));
    
            var dATA_NAME_12Parameter = dATA_NAME_12 != null ?
                new ObjectParameter("DATA_NAME_12", dATA_NAME_12) :
                new ObjectParameter("DATA_NAME_12", typeof(string));
    
            var dATA_VALUE_12Parameter = dATA_VALUE_12 != null ?
                new ObjectParameter("DATA_VALUE_12", dATA_VALUE_12) :
                new ObjectParameter("DATA_VALUE_12", typeof(string));
    
            var dATA_NAME_13Parameter = dATA_NAME_13 != null ?
                new ObjectParameter("DATA_NAME_13", dATA_NAME_13) :
                new ObjectParameter("DATA_NAME_13", typeof(string));
    
            var dATA_VALUE_13Parameter = dATA_VALUE_13 != null ?
                new ObjectParameter("DATA_VALUE_13", dATA_VALUE_13) :
                new ObjectParameter("DATA_VALUE_13", typeof(string));
    
            var dATA_NAME_14Parameter = dATA_NAME_14 != null ?
                new ObjectParameter("DATA_NAME_14", dATA_NAME_14) :
                new ObjectParameter("DATA_NAME_14", typeof(string));
    
            var dATA_VALUE_14Parameter = dATA_VALUE_14 != null ?
                new ObjectParameter("DATA_VALUE_14", dATA_VALUE_14) :
                new ObjectParameter("DATA_VALUE_14", typeof(string));
    
            var dATA_NAME_15Parameter = dATA_NAME_15 != null ?
                new ObjectParameter("DATA_NAME_15", dATA_NAME_15) :
                new ObjectParameter("DATA_NAME_15", typeof(string));
    
            var dATA_VALUE_15Parameter = dATA_VALUE_15 != null ?
                new ObjectParameter("DATA_VALUE_15", dATA_VALUE_15) :
                new ObjectParameter("DATA_VALUE_15", typeof(string));
    
            var dATA_NAME_16Parameter = dATA_NAME_16 != null ?
                new ObjectParameter("DATA_NAME_16", dATA_NAME_16) :
                new ObjectParameter("DATA_NAME_16", typeof(string));
    
            var dATA_VALUE_16Parameter = dATA_VALUE_16 != null ?
                new ObjectParameter("DATA_VALUE_16", dATA_VALUE_16) :
                new ObjectParameter("DATA_VALUE_16", typeof(string));
    
            var dATA_NAME_17Parameter = dATA_NAME_17 != null ?
                new ObjectParameter("DATA_NAME_17", dATA_NAME_17) :
                new ObjectParameter("DATA_NAME_17", typeof(string));
    
            var dATA_VALUE_17Parameter = dATA_VALUE_17 != null ?
                new ObjectParameter("DATA_VALUE_17", dATA_VALUE_17) :
                new ObjectParameter("DATA_VALUE_17", typeof(string));
    
            var dATA_NAME_18Parameter = dATA_NAME_18 != null ?
                new ObjectParameter("DATA_NAME_18", dATA_NAME_18) :
                new ObjectParameter("DATA_NAME_18", typeof(string));
    
            var dATA_VALUE_18Parameter = dATA_VALUE_18 != null ?
                new ObjectParameter("DATA_VALUE_18", dATA_VALUE_18) :
                new ObjectParameter("DATA_VALUE_18", typeof(string));
    
            var dATA_NAME_19Parameter = dATA_NAME_19 != null ?
                new ObjectParameter("DATA_NAME_19", dATA_NAME_19) :
                new ObjectParameter("DATA_NAME_19", typeof(string));
    
            var dATA_VALUE_19Parameter = dATA_VALUE_19 != null ?
                new ObjectParameter("DATA_VALUE_19", dATA_VALUE_19) :
                new ObjectParameter("DATA_VALUE_19", typeof(string));
    
            var dATA_NAME_20Parameter = dATA_NAME_20 != null ?
                new ObjectParameter("DATA_NAME_20", dATA_NAME_20) :
                new ObjectParameter("DATA_NAME_20", typeof(string));
    
            var dATA_VALUE_20Parameter = dATA_VALUE_20 != null ?
                new ObjectParameter("DATA_VALUE_20", dATA_VALUE_20) :
                new ObjectParameter("DATA_VALUE_20", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_EVENT_LOG", eVENT_NAMEParameter, mACHINE_NAMEParameter, pART_SERIAL_NUMBERParameter, oPERATOR_SERIAL_NUMBERParameter, dATA_NAME_1Parameter, dATA_VALUE_1Parameter, dATA_NAME_2Parameter, dATA_VALUE_2Parameter, dATA_NAME_3Parameter, dATA_VALUE_3Parameter, dATA_NAME_4Parameter, dATA_VALUE_4Parameter, dATA_NAME_5Parameter, dATA_VALUE_5Parameter, dATA_NAME_6Parameter, dATA_VALUE_6Parameter, dATA_NAME_7Parameter, dATA_VALUE_7Parameter, dATA_NAME_8Parameter, dATA_VALUE_8Parameter, dATA_NAME_9Parameter, dATA_VALUE_9Parameter, dATA_NAME_10Parameter, dATA_VALUE_10Parameter, dATA_NAME_11Parameter, dATA_VALUE_11Parameter, dATA_NAME_12Parameter, dATA_VALUE_12Parameter, dATA_NAME_13Parameter, dATA_VALUE_13Parameter, dATA_NAME_14Parameter, dATA_VALUE_14Parameter, dATA_NAME_15Parameter, dATA_VALUE_15Parameter, dATA_NAME_16Parameter, dATA_VALUE_16Parameter, dATA_NAME_17Parameter, dATA_VALUE_17Parameter, dATA_NAME_18Parameter, dATA_VALUE_18Parameter, dATA_NAME_19Parameter, dATA_VALUE_19Parameter, dATA_NAME_20Parameter, dATA_VALUE_20Parameter);
        }
    
        public virtual int INSERT_EVENT_LOG_DATA(Nullable<decimal> eVENT_LOG_ID, string dATA_NAME, string dATA_VALUE)
        {
            var eVENT_LOG_IDParameter = eVENT_LOG_ID.HasValue ?
                new ObjectParameter("EVENT_LOG_ID", eVENT_LOG_ID) :
                new ObjectParameter("EVENT_LOG_ID", typeof(decimal));
    
            var dATA_NAMEParameter = dATA_NAME != null ?
                new ObjectParameter("DATA_NAME", dATA_NAME) :
                new ObjectParameter("DATA_NAME", typeof(string));
    
            var dATA_VALUEParameter = dATA_VALUE != null ?
                new ObjectParameter("DATA_VALUE", dATA_VALUE) :
                new ObjectParameter("DATA_VALUE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_EVENT_LOG_DATA", eVENT_LOG_IDParameter, dATA_NAMEParameter, dATA_VALUEParameter);
        }
    
        public virtual int INSERT_EVENT_LOG_NEW(string eVENT_NAME, string mACHINE_NAME, string pART_SERIAL_NUMBER, string oPERATOR_SERIAL_NUMBER, string dATA_NAME_1, string dATA_VALUE_1, string dATA_NAME_2, string dATA_VALUE_2, string dATA_NAME_3, string dATA_VALUE_3, string dATA_NAME_4, string dATA_VALUE_4, string dATA_NAME_5, string dATA_VALUE_5, string dATA_NAME_6, string dATA_VALUE_6, string dATA_NAME_7, string dATA_VALUE_7, string dATA_NAME_8, string dATA_VALUE_8, string dATA_NAME_9, string dATA_VALUE_9, string dATA_NAME_10, string dATA_VALUE_10, string dATA_NAME_11, string dATA_VALUE_11, string dATA_NAME_12, string dATA_VALUE_12, string dATA_NAME_13, string dATA_VALUE_13, string dATA_NAME_14, string dATA_VALUE_14, string dATA_NAME_15, string dATA_VALUE_15, string dATA_NAME_16, string dATA_VALUE_16, string dATA_NAME_17, string dATA_VALUE_17, string dATA_NAME_18, string dATA_VALUE_18, string dATA_NAME_19, string dATA_VALUE_19, string dATA_NAME_20, string dATA_VALUE_20)
        {
            var eVENT_NAMEParameter = eVENT_NAME != null ?
                new ObjectParameter("EVENT_NAME", eVENT_NAME) :
                new ObjectParameter("EVENT_NAME", typeof(string));
    
            var mACHINE_NAMEParameter = mACHINE_NAME != null ?
                new ObjectParameter("MACHINE_NAME", mACHINE_NAME) :
                new ObjectParameter("MACHINE_NAME", typeof(string));
    
            var pART_SERIAL_NUMBERParameter = pART_SERIAL_NUMBER != null ?
                new ObjectParameter("PART_SERIAL_NUMBER", pART_SERIAL_NUMBER) :
                new ObjectParameter("PART_SERIAL_NUMBER", typeof(string));
    
            var oPERATOR_SERIAL_NUMBERParameter = oPERATOR_SERIAL_NUMBER != null ?
                new ObjectParameter("OPERATOR_SERIAL_NUMBER", oPERATOR_SERIAL_NUMBER) :
                new ObjectParameter("OPERATOR_SERIAL_NUMBER", typeof(string));
    
            var dATA_NAME_1Parameter = dATA_NAME_1 != null ?
                new ObjectParameter("DATA_NAME_1", dATA_NAME_1) :
                new ObjectParameter("DATA_NAME_1", typeof(string));
    
            var dATA_VALUE_1Parameter = dATA_VALUE_1 != null ?
                new ObjectParameter("DATA_VALUE_1", dATA_VALUE_1) :
                new ObjectParameter("DATA_VALUE_1", typeof(string));
    
            var dATA_NAME_2Parameter = dATA_NAME_2 != null ?
                new ObjectParameter("DATA_NAME_2", dATA_NAME_2) :
                new ObjectParameter("DATA_NAME_2", typeof(string));
    
            var dATA_VALUE_2Parameter = dATA_VALUE_2 != null ?
                new ObjectParameter("DATA_VALUE_2", dATA_VALUE_2) :
                new ObjectParameter("DATA_VALUE_2", typeof(string));
    
            var dATA_NAME_3Parameter = dATA_NAME_3 != null ?
                new ObjectParameter("DATA_NAME_3", dATA_NAME_3) :
                new ObjectParameter("DATA_NAME_3", typeof(string));
    
            var dATA_VALUE_3Parameter = dATA_VALUE_3 != null ?
                new ObjectParameter("DATA_VALUE_3", dATA_VALUE_3) :
                new ObjectParameter("DATA_VALUE_3", typeof(string));
    
            var dATA_NAME_4Parameter = dATA_NAME_4 != null ?
                new ObjectParameter("DATA_NAME_4", dATA_NAME_4) :
                new ObjectParameter("DATA_NAME_4", typeof(string));
    
            var dATA_VALUE_4Parameter = dATA_VALUE_4 != null ?
                new ObjectParameter("DATA_VALUE_4", dATA_VALUE_4) :
                new ObjectParameter("DATA_VALUE_4", typeof(string));
    
            var dATA_NAME_5Parameter = dATA_NAME_5 != null ?
                new ObjectParameter("DATA_NAME_5", dATA_NAME_5) :
                new ObjectParameter("DATA_NAME_5", typeof(string));
    
            var dATA_VALUE_5Parameter = dATA_VALUE_5 != null ?
                new ObjectParameter("DATA_VALUE_5", dATA_VALUE_5) :
                new ObjectParameter("DATA_VALUE_5", typeof(string));
    
            var dATA_NAME_6Parameter = dATA_NAME_6 != null ?
                new ObjectParameter("DATA_NAME_6", dATA_NAME_6) :
                new ObjectParameter("DATA_NAME_6", typeof(string));
    
            var dATA_VALUE_6Parameter = dATA_VALUE_6 != null ?
                new ObjectParameter("DATA_VALUE_6", dATA_VALUE_6) :
                new ObjectParameter("DATA_VALUE_6", typeof(string));
    
            var dATA_NAME_7Parameter = dATA_NAME_7 != null ?
                new ObjectParameter("DATA_NAME_7", dATA_NAME_7) :
                new ObjectParameter("DATA_NAME_7", typeof(string));
    
            var dATA_VALUE_7Parameter = dATA_VALUE_7 != null ?
                new ObjectParameter("DATA_VALUE_7", dATA_VALUE_7) :
                new ObjectParameter("DATA_VALUE_7", typeof(string));
    
            var dATA_NAME_8Parameter = dATA_NAME_8 != null ?
                new ObjectParameter("DATA_NAME_8", dATA_NAME_8) :
                new ObjectParameter("DATA_NAME_8", typeof(string));
    
            var dATA_VALUE_8Parameter = dATA_VALUE_8 != null ?
                new ObjectParameter("DATA_VALUE_8", dATA_VALUE_8) :
                new ObjectParameter("DATA_VALUE_8", typeof(string));
    
            var dATA_NAME_9Parameter = dATA_NAME_9 != null ?
                new ObjectParameter("DATA_NAME_9", dATA_NAME_9) :
                new ObjectParameter("DATA_NAME_9", typeof(string));
    
            var dATA_VALUE_9Parameter = dATA_VALUE_9 != null ?
                new ObjectParameter("DATA_VALUE_9", dATA_VALUE_9) :
                new ObjectParameter("DATA_VALUE_9", typeof(string));
    
            var dATA_NAME_10Parameter = dATA_NAME_10 != null ?
                new ObjectParameter("DATA_NAME_10", dATA_NAME_10) :
                new ObjectParameter("DATA_NAME_10", typeof(string));
    
            var dATA_VALUE_10Parameter = dATA_VALUE_10 != null ?
                new ObjectParameter("DATA_VALUE_10", dATA_VALUE_10) :
                new ObjectParameter("DATA_VALUE_10", typeof(string));
    
            var dATA_NAME_11Parameter = dATA_NAME_11 != null ?
                new ObjectParameter("DATA_NAME_11", dATA_NAME_11) :
                new ObjectParameter("DATA_NAME_11", typeof(string));
    
            var dATA_VALUE_11Parameter = dATA_VALUE_11 != null ?
                new ObjectParameter("DATA_VALUE_11", dATA_VALUE_11) :
                new ObjectParameter("DATA_VALUE_11", typeof(string));
    
            var dATA_NAME_12Parameter = dATA_NAME_12 != null ?
                new ObjectParameter("DATA_NAME_12", dATA_NAME_12) :
                new ObjectParameter("DATA_NAME_12", typeof(string));
    
            var dATA_VALUE_12Parameter = dATA_VALUE_12 != null ?
                new ObjectParameter("DATA_VALUE_12", dATA_VALUE_12) :
                new ObjectParameter("DATA_VALUE_12", typeof(string));
    
            var dATA_NAME_13Parameter = dATA_NAME_13 != null ?
                new ObjectParameter("DATA_NAME_13", dATA_NAME_13) :
                new ObjectParameter("DATA_NAME_13", typeof(string));
    
            var dATA_VALUE_13Parameter = dATA_VALUE_13 != null ?
                new ObjectParameter("DATA_VALUE_13", dATA_VALUE_13) :
                new ObjectParameter("DATA_VALUE_13", typeof(string));
    
            var dATA_NAME_14Parameter = dATA_NAME_14 != null ?
                new ObjectParameter("DATA_NAME_14", dATA_NAME_14) :
                new ObjectParameter("DATA_NAME_14", typeof(string));
    
            var dATA_VALUE_14Parameter = dATA_VALUE_14 != null ?
                new ObjectParameter("DATA_VALUE_14", dATA_VALUE_14) :
                new ObjectParameter("DATA_VALUE_14", typeof(string));
    
            var dATA_NAME_15Parameter = dATA_NAME_15 != null ?
                new ObjectParameter("DATA_NAME_15", dATA_NAME_15) :
                new ObjectParameter("DATA_NAME_15", typeof(string));
    
            var dATA_VALUE_15Parameter = dATA_VALUE_15 != null ?
                new ObjectParameter("DATA_VALUE_15", dATA_VALUE_15) :
                new ObjectParameter("DATA_VALUE_15", typeof(string));
    
            var dATA_NAME_16Parameter = dATA_NAME_16 != null ?
                new ObjectParameter("DATA_NAME_16", dATA_NAME_16) :
                new ObjectParameter("DATA_NAME_16", typeof(string));
    
            var dATA_VALUE_16Parameter = dATA_VALUE_16 != null ?
                new ObjectParameter("DATA_VALUE_16", dATA_VALUE_16) :
                new ObjectParameter("DATA_VALUE_16", typeof(string));
    
            var dATA_NAME_17Parameter = dATA_NAME_17 != null ?
                new ObjectParameter("DATA_NAME_17", dATA_NAME_17) :
                new ObjectParameter("DATA_NAME_17", typeof(string));
    
            var dATA_VALUE_17Parameter = dATA_VALUE_17 != null ?
                new ObjectParameter("DATA_VALUE_17", dATA_VALUE_17) :
                new ObjectParameter("DATA_VALUE_17", typeof(string));
    
            var dATA_NAME_18Parameter = dATA_NAME_18 != null ?
                new ObjectParameter("DATA_NAME_18", dATA_NAME_18) :
                new ObjectParameter("DATA_NAME_18", typeof(string));
    
            var dATA_VALUE_18Parameter = dATA_VALUE_18 != null ?
                new ObjectParameter("DATA_VALUE_18", dATA_VALUE_18) :
                new ObjectParameter("DATA_VALUE_18", typeof(string));
    
            var dATA_NAME_19Parameter = dATA_NAME_19 != null ?
                new ObjectParameter("DATA_NAME_19", dATA_NAME_19) :
                new ObjectParameter("DATA_NAME_19", typeof(string));
    
            var dATA_VALUE_19Parameter = dATA_VALUE_19 != null ?
                new ObjectParameter("DATA_VALUE_19", dATA_VALUE_19) :
                new ObjectParameter("DATA_VALUE_19", typeof(string));
    
            var dATA_NAME_20Parameter = dATA_NAME_20 != null ?
                new ObjectParameter("DATA_NAME_20", dATA_NAME_20) :
                new ObjectParameter("DATA_NAME_20", typeof(string));
    
            var dATA_VALUE_20Parameter = dATA_VALUE_20 != null ?
                new ObjectParameter("DATA_VALUE_20", dATA_VALUE_20) :
                new ObjectParameter("DATA_VALUE_20", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_EVENT_LOG_NEW", eVENT_NAMEParameter, mACHINE_NAMEParameter, pART_SERIAL_NUMBERParameter, oPERATOR_SERIAL_NUMBERParameter, dATA_NAME_1Parameter, dATA_VALUE_1Parameter, dATA_NAME_2Parameter, dATA_VALUE_2Parameter, dATA_NAME_3Parameter, dATA_VALUE_3Parameter, dATA_NAME_4Parameter, dATA_VALUE_4Parameter, dATA_NAME_5Parameter, dATA_VALUE_5Parameter, dATA_NAME_6Parameter, dATA_VALUE_6Parameter, dATA_NAME_7Parameter, dATA_VALUE_7Parameter, dATA_NAME_8Parameter, dATA_VALUE_8Parameter, dATA_NAME_9Parameter, dATA_VALUE_9Parameter, dATA_NAME_10Parameter, dATA_VALUE_10Parameter, dATA_NAME_11Parameter, dATA_VALUE_11Parameter, dATA_NAME_12Parameter, dATA_VALUE_12Parameter, dATA_NAME_13Parameter, dATA_VALUE_13Parameter, dATA_NAME_14Parameter, dATA_VALUE_14Parameter, dATA_NAME_15Parameter, dATA_VALUE_15Parameter, dATA_NAME_16Parameter, dATA_VALUE_16Parameter, dATA_NAME_17Parameter, dATA_VALUE_17Parameter, dATA_NAME_18Parameter, dATA_VALUE_18Parameter, dATA_NAME_19Parameter, dATA_VALUE_19Parameter, dATA_NAME_20Parameter, dATA_VALUE_20Parameter);
        }
    
        public virtual int INSERT_EVENT_LOG_OLD(string eVENT_NAME, string mACHINE_NAME, string pART_SERIAL_NUMBER, string oPERATOR_SERIAL_NUMBER, string dATA_NAME_1, string dATA_VALUE_1, string dATA_NAME_2, string dATA_VALUE_2, string dATA_NAME_3, string dATA_VALUE_3, string dATA_NAME_4, string dATA_VALUE_4, string dATA_NAME_5, string dATA_VALUE_5, string dATA_NAME_6, string dATA_VALUE_6, string dATA_NAME_7, string dATA_VALUE_7, string dATA_NAME_8, string dATA_VALUE_8, string dATA_NAME_9, string dATA_VALUE_9, string dATA_NAME_10, string dATA_VALUE_10, string dATA_NAME_11, string dATA_VALUE_11, string dATA_NAME_12, string dATA_VALUE_12, string dATA_NAME_13, string dATA_VALUE_13, string dATA_NAME_14, string dATA_VALUE_14, string dATA_NAME_15, string dATA_VALUE_15, string dATA_NAME_16, string dATA_VALUE_16, string dATA_NAME_17, string dATA_VALUE_17, string dATA_NAME_18, string dATA_VALUE_18, string dATA_NAME_19, string dATA_VALUE_19, string dATA_NAME_20, string dATA_VALUE_20)
        {
            var eVENT_NAMEParameter = eVENT_NAME != null ?
                new ObjectParameter("EVENT_NAME", eVENT_NAME) :
                new ObjectParameter("EVENT_NAME", typeof(string));
    
            var mACHINE_NAMEParameter = mACHINE_NAME != null ?
                new ObjectParameter("MACHINE_NAME", mACHINE_NAME) :
                new ObjectParameter("MACHINE_NAME", typeof(string));
    
            var pART_SERIAL_NUMBERParameter = pART_SERIAL_NUMBER != null ?
                new ObjectParameter("PART_SERIAL_NUMBER", pART_SERIAL_NUMBER) :
                new ObjectParameter("PART_SERIAL_NUMBER", typeof(string));
    
            var oPERATOR_SERIAL_NUMBERParameter = oPERATOR_SERIAL_NUMBER != null ?
                new ObjectParameter("OPERATOR_SERIAL_NUMBER", oPERATOR_SERIAL_NUMBER) :
                new ObjectParameter("OPERATOR_SERIAL_NUMBER", typeof(string));
    
            var dATA_NAME_1Parameter = dATA_NAME_1 != null ?
                new ObjectParameter("DATA_NAME_1", dATA_NAME_1) :
                new ObjectParameter("DATA_NAME_1", typeof(string));
    
            var dATA_VALUE_1Parameter = dATA_VALUE_1 != null ?
                new ObjectParameter("DATA_VALUE_1", dATA_VALUE_1) :
                new ObjectParameter("DATA_VALUE_1", typeof(string));
    
            var dATA_NAME_2Parameter = dATA_NAME_2 != null ?
                new ObjectParameter("DATA_NAME_2", dATA_NAME_2) :
                new ObjectParameter("DATA_NAME_2", typeof(string));
    
            var dATA_VALUE_2Parameter = dATA_VALUE_2 != null ?
                new ObjectParameter("DATA_VALUE_2", dATA_VALUE_2) :
                new ObjectParameter("DATA_VALUE_2", typeof(string));
    
            var dATA_NAME_3Parameter = dATA_NAME_3 != null ?
                new ObjectParameter("DATA_NAME_3", dATA_NAME_3) :
                new ObjectParameter("DATA_NAME_3", typeof(string));
    
            var dATA_VALUE_3Parameter = dATA_VALUE_3 != null ?
                new ObjectParameter("DATA_VALUE_3", dATA_VALUE_3) :
                new ObjectParameter("DATA_VALUE_3", typeof(string));
    
            var dATA_NAME_4Parameter = dATA_NAME_4 != null ?
                new ObjectParameter("DATA_NAME_4", dATA_NAME_4) :
                new ObjectParameter("DATA_NAME_4", typeof(string));
    
            var dATA_VALUE_4Parameter = dATA_VALUE_4 != null ?
                new ObjectParameter("DATA_VALUE_4", dATA_VALUE_4) :
                new ObjectParameter("DATA_VALUE_4", typeof(string));
    
            var dATA_NAME_5Parameter = dATA_NAME_5 != null ?
                new ObjectParameter("DATA_NAME_5", dATA_NAME_5) :
                new ObjectParameter("DATA_NAME_5", typeof(string));
    
            var dATA_VALUE_5Parameter = dATA_VALUE_5 != null ?
                new ObjectParameter("DATA_VALUE_5", dATA_VALUE_5) :
                new ObjectParameter("DATA_VALUE_5", typeof(string));
    
            var dATA_NAME_6Parameter = dATA_NAME_6 != null ?
                new ObjectParameter("DATA_NAME_6", dATA_NAME_6) :
                new ObjectParameter("DATA_NAME_6", typeof(string));
    
            var dATA_VALUE_6Parameter = dATA_VALUE_6 != null ?
                new ObjectParameter("DATA_VALUE_6", dATA_VALUE_6) :
                new ObjectParameter("DATA_VALUE_6", typeof(string));
    
            var dATA_NAME_7Parameter = dATA_NAME_7 != null ?
                new ObjectParameter("DATA_NAME_7", dATA_NAME_7) :
                new ObjectParameter("DATA_NAME_7", typeof(string));
    
            var dATA_VALUE_7Parameter = dATA_VALUE_7 != null ?
                new ObjectParameter("DATA_VALUE_7", dATA_VALUE_7) :
                new ObjectParameter("DATA_VALUE_7", typeof(string));
    
            var dATA_NAME_8Parameter = dATA_NAME_8 != null ?
                new ObjectParameter("DATA_NAME_8", dATA_NAME_8) :
                new ObjectParameter("DATA_NAME_8", typeof(string));
    
            var dATA_VALUE_8Parameter = dATA_VALUE_8 != null ?
                new ObjectParameter("DATA_VALUE_8", dATA_VALUE_8) :
                new ObjectParameter("DATA_VALUE_8", typeof(string));
    
            var dATA_NAME_9Parameter = dATA_NAME_9 != null ?
                new ObjectParameter("DATA_NAME_9", dATA_NAME_9) :
                new ObjectParameter("DATA_NAME_9", typeof(string));
    
            var dATA_VALUE_9Parameter = dATA_VALUE_9 != null ?
                new ObjectParameter("DATA_VALUE_9", dATA_VALUE_9) :
                new ObjectParameter("DATA_VALUE_9", typeof(string));
    
            var dATA_NAME_10Parameter = dATA_NAME_10 != null ?
                new ObjectParameter("DATA_NAME_10", dATA_NAME_10) :
                new ObjectParameter("DATA_NAME_10", typeof(string));
    
            var dATA_VALUE_10Parameter = dATA_VALUE_10 != null ?
                new ObjectParameter("DATA_VALUE_10", dATA_VALUE_10) :
                new ObjectParameter("DATA_VALUE_10", typeof(string));
    
            var dATA_NAME_11Parameter = dATA_NAME_11 != null ?
                new ObjectParameter("DATA_NAME_11", dATA_NAME_11) :
                new ObjectParameter("DATA_NAME_11", typeof(string));
    
            var dATA_VALUE_11Parameter = dATA_VALUE_11 != null ?
                new ObjectParameter("DATA_VALUE_11", dATA_VALUE_11) :
                new ObjectParameter("DATA_VALUE_11", typeof(string));
    
            var dATA_NAME_12Parameter = dATA_NAME_12 != null ?
                new ObjectParameter("DATA_NAME_12", dATA_NAME_12) :
                new ObjectParameter("DATA_NAME_12", typeof(string));
    
            var dATA_VALUE_12Parameter = dATA_VALUE_12 != null ?
                new ObjectParameter("DATA_VALUE_12", dATA_VALUE_12) :
                new ObjectParameter("DATA_VALUE_12", typeof(string));
    
            var dATA_NAME_13Parameter = dATA_NAME_13 != null ?
                new ObjectParameter("DATA_NAME_13", dATA_NAME_13) :
                new ObjectParameter("DATA_NAME_13", typeof(string));
    
            var dATA_VALUE_13Parameter = dATA_VALUE_13 != null ?
                new ObjectParameter("DATA_VALUE_13", dATA_VALUE_13) :
                new ObjectParameter("DATA_VALUE_13", typeof(string));
    
            var dATA_NAME_14Parameter = dATA_NAME_14 != null ?
                new ObjectParameter("DATA_NAME_14", dATA_NAME_14) :
                new ObjectParameter("DATA_NAME_14", typeof(string));
    
            var dATA_VALUE_14Parameter = dATA_VALUE_14 != null ?
                new ObjectParameter("DATA_VALUE_14", dATA_VALUE_14) :
                new ObjectParameter("DATA_VALUE_14", typeof(string));
    
            var dATA_NAME_15Parameter = dATA_NAME_15 != null ?
                new ObjectParameter("DATA_NAME_15", dATA_NAME_15) :
                new ObjectParameter("DATA_NAME_15", typeof(string));
    
            var dATA_VALUE_15Parameter = dATA_VALUE_15 != null ?
                new ObjectParameter("DATA_VALUE_15", dATA_VALUE_15) :
                new ObjectParameter("DATA_VALUE_15", typeof(string));
    
            var dATA_NAME_16Parameter = dATA_NAME_16 != null ?
                new ObjectParameter("DATA_NAME_16", dATA_NAME_16) :
                new ObjectParameter("DATA_NAME_16", typeof(string));
    
            var dATA_VALUE_16Parameter = dATA_VALUE_16 != null ?
                new ObjectParameter("DATA_VALUE_16", dATA_VALUE_16) :
                new ObjectParameter("DATA_VALUE_16", typeof(string));
    
            var dATA_NAME_17Parameter = dATA_NAME_17 != null ?
                new ObjectParameter("DATA_NAME_17", dATA_NAME_17) :
                new ObjectParameter("DATA_NAME_17", typeof(string));
    
            var dATA_VALUE_17Parameter = dATA_VALUE_17 != null ?
                new ObjectParameter("DATA_VALUE_17", dATA_VALUE_17) :
                new ObjectParameter("DATA_VALUE_17", typeof(string));
    
            var dATA_NAME_18Parameter = dATA_NAME_18 != null ?
                new ObjectParameter("DATA_NAME_18", dATA_NAME_18) :
                new ObjectParameter("DATA_NAME_18", typeof(string));
    
            var dATA_VALUE_18Parameter = dATA_VALUE_18 != null ?
                new ObjectParameter("DATA_VALUE_18", dATA_VALUE_18) :
                new ObjectParameter("DATA_VALUE_18", typeof(string));
    
            var dATA_NAME_19Parameter = dATA_NAME_19 != null ?
                new ObjectParameter("DATA_NAME_19", dATA_NAME_19) :
                new ObjectParameter("DATA_NAME_19", typeof(string));
    
            var dATA_VALUE_19Parameter = dATA_VALUE_19 != null ?
                new ObjectParameter("DATA_VALUE_19", dATA_VALUE_19) :
                new ObjectParameter("DATA_VALUE_19", typeof(string));
    
            var dATA_NAME_20Parameter = dATA_NAME_20 != null ?
                new ObjectParameter("DATA_NAME_20", dATA_NAME_20) :
                new ObjectParameter("DATA_NAME_20", typeof(string));
    
            var dATA_VALUE_20Parameter = dATA_VALUE_20 != null ?
                new ObjectParameter("DATA_VALUE_20", dATA_VALUE_20) :
                new ObjectParameter("DATA_VALUE_20", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_EVENT_LOG_OLD", eVENT_NAMEParameter, mACHINE_NAMEParameter, pART_SERIAL_NUMBERParameter, oPERATOR_SERIAL_NUMBERParameter, dATA_NAME_1Parameter, dATA_VALUE_1Parameter, dATA_NAME_2Parameter, dATA_VALUE_2Parameter, dATA_NAME_3Parameter, dATA_VALUE_3Parameter, dATA_NAME_4Parameter, dATA_VALUE_4Parameter, dATA_NAME_5Parameter, dATA_VALUE_5Parameter, dATA_NAME_6Parameter, dATA_VALUE_6Parameter, dATA_NAME_7Parameter, dATA_VALUE_7Parameter, dATA_NAME_8Parameter, dATA_VALUE_8Parameter, dATA_NAME_9Parameter, dATA_VALUE_9Parameter, dATA_NAME_10Parameter, dATA_VALUE_10Parameter, dATA_NAME_11Parameter, dATA_VALUE_11Parameter, dATA_NAME_12Parameter, dATA_VALUE_12Parameter, dATA_NAME_13Parameter, dATA_VALUE_13Parameter, dATA_NAME_14Parameter, dATA_VALUE_14Parameter, dATA_NAME_15Parameter, dATA_VALUE_15Parameter, dATA_NAME_16Parameter, dATA_VALUE_16Parameter, dATA_NAME_17Parameter, dATA_VALUE_17Parameter, dATA_NAME_18Parameter, dATA_VALUE_18Parameter, dATA_NAME_19Parameter, dATA_VALUE_19Parameter, dATA_NAME_20Parameter, dATA_VALUE_20Parameter);
        }
    
        public virtual int INSERT_GOODTIRE_LOG(Nullable<decimal> p_EVENT_LOG_ID)
        {
            var p_EVENT_LOG_IDParameter = p_EVENT_LOG_ID.HasValue ?
                new ObjectParameter("P_EVENT_LOG_ID", p_EVENT_LOG_ID) :
                new ObjectParameter("P_EVENT_LOG_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_GOODTIRE_LOG", p_EVENT_LOG_IDParameter);
        }
    
        public virtual int INSERT_GTI_EXPORT_CURED(string p_PART_SERIAL_NUMBER, string p_OPERATOR_SERIAL_NUMBER, string p_MACHINE_NAME)
        {
            var p_PART_SERIAL_NUMBERParameter = p_PART_SERIAL_NUMBER != null ?
                new ObjectParameter("P_PART_SERIAL_NUMBER", p_PART_SERIAL_NUMBER) :
                new ObjectParameter("P_PART_SERIAL_NUMBER", typeof(string));
    
            var p_OPERATOR_SERIAL_NUMBERParameter = p_OPERATOR_SERIAL_NUMBER != null ?
                new ObjectParameter("P_OPERATOR_SERIAL_NUMBER", p_OPERATOR_SERIAL_NUMBER) :
                new ObjectParameter("P_OPERATOR_SERIAL_NUMBER", typeof(string));
    
            var p_MACHINE_NAMEParameter = p_MACHINE_NAME != null ?
                new ObjectParameter("P_MACHINE_NAME", p_MACHINE_NAME) :
                new ObjectParameter("P_MACHINE_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_GTI_EXPORT_CURED", p_PART_SERIAL_NUMBERParameter, p_OPERATOR_SERIAL_NUMBERParameter, p_MACHINE_NAMEParameter);
        }
    
        public virtual int INSERT_NOTIFICATION_LOG(string p_MACHINE, string p_OPERATOR_SERIAL, string p_CALL_TYPE, string p_PRIORITY, string p_WORK_CENTER, string p_SYMPTOM, string p_COMMENT)
        {
            var p_MACHINEParameter = p_MACHINE != null ?
                new ObjectParameter("P_MACHINE", p_MACHINE) :
                new ObjectParameter("P_MACHINE", typeof(string));
    
            var p_OPERATOR_SERIALParameter = p_OPERATOR_SERIAL != null ?
                new ObjectParameter("P_OPERATOR_SERIAL", p_OPERATOR_SERIAL) :
                new ObjectParameter("P_OPERATOR_SERIAL", typeof(string));
    
            var p_CALL_TYPEParameter = p_CALL_TYPE != null ?
                new ObjectParameter("P_CALL_TYPE", p_CALL_TYPE) :
                new ObjectParameter("P_CALL_TYPE", typeof(string));
    
            var p_PRIORITYParameter = p_PRIORITY != null ?
                new ObjectParameter("P_PRIORITY", p_PRIORITY) :
                new ObjectParameter("P_PRIORITY", typeof(string));
    
            var p_WORK_CENTERParameter = p_WORK_CENTER != null ?
                new ObjectParameter("P_WORK_CENTER", p_WORK_CENTER) :
                new ObjectParameter("P_WORK_CENTER", typeof(string));
    
            var p_SYMPTOMParameter = p_SYMPTOM != null ?
                new ObjectParameter("P_SYMPTOM", p_SYMPTOM) :
                new ObjectParameter("P_SYMPTOM", typeof(string));
    
            var p_COMMENTParameter = p_COMMENT != null ?
                new ObjectParameter("P_COMMENT", p_COMMENT) :
                new ObjectParameter("P_COMMENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_NOTIFICATION_LOG", p_MACHINEParameter, p_OPERATOR_SERIALParameter, p_CALL_TYPEParameter, p_PRIORITYParameter, p_WORK_CENTERParameter, p_SYMPTOMParameter, p_COMMENTParameter);
        }
    
        public virtual int SELECT_OP_BUILD_FINISH_PCT(Nullable<System.DateTime> p_START_DATE, Nullable<System.DateTime> p_END_DATE)
        {
            var p_START_DATEParameter = p_START_DATE.HasValue ?
                new ObjectParameter("P_START_DATE", p_START_DATE) :
                new ObjectParameter("P_START_DATE", typeof(System.DateTime));
    
            var p_END_DATEParameter = p_END_DATE.HasValue ?
                new ObjectParameter("P_END_DATE", p_END_DATE) :
                new ObjectParameter("P_END_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECT_OP_BUILD_FINISH_PCT", p_START_DATEParameter, p_END_DATEParameter);
        }
    
        public virtual int SELECT_PART_HISTORY(string p_PART_SERIAL_NUMBER)
        {
            var p_PART_SERIAL_NUMBERParameter = p_PART_SERIAL_NUMBER != null ?
                new ObjectParameter("P_PART_SERIAL_NUMBER", p_PART_SERIAL_NUMBER) :
                new ObjectParameter("P_PART_SERIAL_NUMBER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECT_PART_HISTORY", p_PART_SERIAL_NUMBERParameter);
        }
    
        public virtual int UPDATE_CURING_SETUP(Nullable<decimal> p_DEPARTMENT, string p_POT, string p_GREEN_TIRE_NUMBER, string p_TOTAL_CYCLE_TIME, string p_MOLD, string p_CURE_NUMBER, string p_SKU)
        {
            var p_DEPARTMENTParameter = p_DEPARTMENT.HasValue ?
                new ObjectParameter("P_DEPARTMENT", p_DEPARTMENT) :
                new ObjectParameter("P_DEPARTMENT", typeof(decimal));
    
            var p_POTParameter = p_POT != null ?
                new ObjectParameter("P_POT", p_POT) :
                new ObjectParameter("P_POT", typeof(string));
    
            var p_GREEN_TIRE_NUMBERParameter = p_GREEN_TIRE_NUMBER != null ?
                new ObjectParameter("P_GREEN_TIRE_NUMBER", p_GREEN_TIRE_NUMBER) :
                new ObjectParameter("P_GREEN_TIRE_NUMBER", typeof(string));
    
            var p_TOTAL_CYCLE_TIMEParameter = p_TOTAL_CYCLE_TIME != null ?
                new ObjectParameter("P_TOTAL_CYCLE_TIME", p_TOTAL_CYCLE_TIME) :
                new ObjectParameter("P_TOTAL_CYCLE_TIME", typeof(string));
    
            var p_MOLDParameter = p_MOLD != null ?
                new ObjectParameter("P_MOLD", p_MOLD) :
                new ObjectParameter("P_MOLD", typeof(string));
    
            var p_CURE_NUMBERParameter = p_CURE_NUMBER != null ?
                new ObjectParameter("P_CURE_NUMBER", p_CURE_NUMBER) :
                new ObjectParameter("P_CURE_NUMBER", typeof(string));
    
            var p_SKUParameter = p_SKU != null ?
                new ObjectParameter("P_SKU", p_SKU) :
                new ObjectParameter("P_SKU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_CURING_SETUP", p_DEPARTMENTParameter, p_POTParameter, p_GREEN_TIRE_NUMBERParameter, p_TOTAL_CYCLE_TIMEParameter, p_MOLDParameter, p_CURE_NUMBERParameter, p_SKUParameter);
        }
    }
}
