//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOWNTIME_ORPHANS
    {
        public decimal STARTLOGID { get; set; }
        public Nullable<decimal> ENDLOGID { get; set; }
        public System.DateTime STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public string MACHINE { get; set; }
        public string PART { get; set; }
        public string CONTAINERTYPESTART { get; set; }
        public string CONTAINERTYPEEND { get; set; }
        public string STARTCONTAINER { get; set; }
        public string ENDCONTAINER { get; set; }
        public string STARTEVENTCODE { get; set; }
        public string START_COMMENT { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
