//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT_LOG_VIEW
    {
        public decimal LOG_ID { get; set; }
        public string LOG_DATE { get; set; }
        public Nullable<decimal> EVENT_ID { get; set; }
        public string EVENT { get; set; }
        public string EVENT_DESCRIPTION { get; set; }
        public Nullable<decimal> MACHINE_ID { get; set; }
        public string MACHINE { get; set; }
        public string MACHINE_DESCRIPTION { get; set; }
        public string TIRE_CREATED { get; set; }
        public Nullable<decimal> PART_ID { get; set; }
        public string TIRE_SERIAL_NUMBER { get; set; }
        public string GREEN_TIRE_NUMBER { get; set; }
        public string GOODYEAR_SERIAL_NUMBER { get; set; }
        public Nullable<decimal> OPERATOR_ID { get; set; }
        public string OPERATOR_SERIAL_NUMBER { get; set; }
        public string OPERATOR_NAME { get; set; }
        public string DATA_NAME { get; set; }
        public string DATA_DESCRIPTION { get; set; }
        public string DATA_VALUE { get; set; }
    }
}
