//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT_CARD_LOG
    {
        public decimal EVENT_CARD_LOG_ID { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public Nullable<decimal> DEPT { get; set; }
        public string BADGE_NUMBER { get; set; }
        public string MACHINE { get; set; }
        public string LABOR_CODE { get; set; }
        public Nullable<decimal> GTN { get; set; }
        public Nullable<decimal> LOT { get; set; }
        public string EXPLANATION { get; set; }
        public string PART_SERIAL { get; set; }
        public Nullable<decimal> DOWNTIME_CONTAINER { get; set; }
    }
}
