//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT_DATA
    {
        public decimal EVENT_DATA_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string UNIT { get; set; }
    }
}
