//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT_LOG_VIEW_WITH_SHIFT_NEW
    {
        public decimal EVENT_LOG_ID { get; set; }
        public System.DateTime EVENT_CREATED { get; set; }
        public Nullable<decimal> EVENT_ID { get; set; }
        public string EVENT_NAME { get; set; }
        public Nullable<decimal> MACHINE_ID { get; set; }
        public string MACHINE_NAME { get; set; }
        public Nullable<decimal> PART_ID { get; set; }
        public Nullable<System.DateTime> PART_CREATED { get; set; }
        public string PART_LABEL { get; set; }
        public string GREEN_TIRE_NUMBER { get; set; }
        public string GOODYEAR_SERIAL_NUMBER { get; set; }
        public Nullable<decimal> OPERATOR_ID { get; set; }
        public string EMPLOYEE_NUMBER { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<decimal> EVENT_DATA_ID { get; set; }
        public string DATA_NAME { get; set; }
        public string DATA_VALUE { get; set; }
        public System.DateTime WORK_DATE { get; set; }
        public string WORK_SHIFT { get; set; }
    }
}
