//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT_LAST_GOODTIRE_SECONDS
    {
        public decimal EVENT_LOG_ID { get; set; }
        public Nullable<System.DateTime> WORK_DATE { get; set; }
        public string WORK_SHIFT { get; set; }
        public string MACHINE_NAME { get; set; }
        public System.DateTime GOOD_TIRE_TIMESTAMP { get; set; }
        public Nullable<System.DateTime> LAST_EVENT_TIME { get; set; }
        public Nullable<decimal> ELAPSED_SECONDS { get; set; }
    }
}
