//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINISHING_PIVOT_VIEW
    {
        public decimal EVENT_LOG_ID { get; set; }
        public System.DateTime CREATED { get; set; }
        public decimal EVENT_ID { get; set; }
        public Nullable<decimal> MACHINE_ID { get; set; }
        public Nullable<decimal> OPERATOR_ID { get; set; }
        public Nullable<decimal> PART_ID { get; set; }
        public string PART_SERIAL_NUMBER { get; set; }
        public string GREEN_TIRE_NUMBER { get; set; }
        public string GOODYEAR_SERIAL_NUMBER { get; set; }
        public string MACHINE_NAME { get; set; }
        public string MACHINE_DESCRIPTION { get; set; }
        public string TIRE_GRADE { get; set; }
        public string UPPER_MAG { get; set; }
        public string STATIC_ANGLE { get; set; }
        public string BOTTOM_PEAK { get; set; }
        public string TOP_PEAK { get; set; }
        public string RADIAL_1ST_HARM { get; set; }
        public string RADIAL_PEAK { get; set; }
        public string STATIC_MAG { get; set; }
        public string LOWER_MAG { get; set; }
        public string COUPLE_MAG { get; set; }
        public string WEIGHT { get; set; }
    }
}
