//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOODTIRE_LOG
    {
        public decimal GOODTIRE_LOG_ID { get; set; }
        public Nullable<decimal> EVENT_LOG_ID { get; set; }
        public Nullable<System.DateTime> EVENT_LOG_CREATED { get; set; }
        public Nullable<decimal> MACHINE_ID { get; set; }
        public Nullable<decimal> PART_ID { get; set; }
    }
}
