//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GREEN_TIRE
    {
        public decimal GREEN_TIRE_ID { get; set; }
        public string GREEN_TIRE_NUMBER { get; set; }
        public string SKU { get; set; }
        public string TIRE_CODE { get; set; }
    }
}
