//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenTire
    {
        public decimal Id { get; set; }
        public string GreenTireNumber { get; set; }
        public string SKU { get; set; }
        public string TireCode { get; set; }
    }
}
