//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GTI_CURED_VIEW
    {
        public decimal ROW_SEQ { get; set; }
        public string POT_NUMBER { get; set; }
        public string GREEN_TIRE_NUMBER { get; set; }
        public string LABEL { get; set; }
        public string OPERATOR_WINPAK_ID { get; set; }
        public string LABEL_SCANNED { get; set; }
        public string CREATED { get; set; }
        public string MOLD_NUMBER { get; set; }
        public Nullable<decimal> OC_TIME { get; set; }
        public Nullable<decimal> TOTAL_CYCLE_TIME { get; set; }
        public Nullable<decimal> CURE_TIME { get; set; }
        public decimal PROCESS_STATUS { get; set; }
        public string LAST_UPDATED { get; set; }
        public string DEPARTMENT { get; set; }
        public string AREA { get; set; }
    }
}
