//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GTN_AND_OPERATOR
    {
        public string GOODYEAR_SERIAL_NUMBER { get; set; }
        public string GREEN_TIRE_NUMBER { get; set; }
        public string OPERATOR_NAME { get; set; }
        public string OPERATOR_SERIAL_NUMBER { get; set; }
    }
}
