//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MACHINE_SCAN_SCORE
    {
        public decimal EVENT_LOG_ID { get; set; }
        public Nullable<decimal> GOOD_READS { get; set; }
        public Nullable<decimal> BAD_READS { get; set; }
    }
}
