//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MACHINE_COUNT_VIEW
    {
        public decimal MACHINE_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> DEPARTMENT_ID { get; set; }
        public Nullable<decimal> EVENT_TOTAL { get; set; }
    }
}
