//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERATOR_PARTS_BUILD_FINISH
    {
        public decimal OPERATOR_ID { get; set; }
        public decimal BUILD_PART_ID { get; set; }
        public Nullable<decimal> FINISH_PART_ID { get; set; }
    }
}
