//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERATOR_GOOD_TIRE_COUNT_VIEW
    {
        public decimal OPERATOR_ID { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public string NAME { get; set; }
        public string EMPLOYEE_NUMBER { get; set; }
        public Nullable<decimal> EVENT_COUNT { get; set; }
    }
}
