//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART
    {
        public PART()
        {
            this.EVENT_LOG = new HashSet<EVENT_LOG>();
        }
    
        public decimal PART_ID { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public string GREEN_TIRE_NUMBER { get; set; }
        public string GOODYEAR_SERIAL_NUMBER { get; set; }
        public System.DateTime CREATED { get; set; }
    
        public virtual ICollection<EVENT_LOG> EVENT_LOG { get; set; }
    }
}
