//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public Part()
        {
            this.EventLog = new HashSet<EVENT_LOG>();
            this.PART_HISTORY = new HashSet<PART_HISTORY>();
        }
    
        public decimal Id { get; set; }
        public string SerialNumber { get; set; }
        public string GreenTireNumber { get; set; }
        public string GoodyearSerialNumber { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual ICollection<EVENT_LOG> EventLog { get; set; }
        public virtual ICollection<PART_HISTORY> PART_HISTORY { get; set; }
    }
}
