//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART_EVENT_VIEW
    {
        public decimal EVENT_LOG_ID { get; set; }
        public System.DateTime EVENT_LOG_CREATED { get; set; }
        public string EVENT_NAME { get; set; }
        public string PART_SERIAL_NUMBER { get; set; }
        public string MACHINE_NAME { get; set; }
    }
}
