//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART_BUILD_CURE_VIEW
    {
        public string PART_SERIAL_NUMBER { get; set; }
        public string GREEN_TIRE_NUMBER { get; set; }
        public string GOODYEAR_SERIAL_NUMBER { get; set; }
        public string BUILD_MACHINE { get; set; }
        public string CURE_MACHINE { get; set; }
        public string BUILD_MACHINE_NUMBER { get; set; }
        public string CURE_MACHINE_NUMBER { get; set; }
        public string BUILD_OPERATOR { get; set; }
        public string CURE_OPERATOR { get; set; }
        public string MOLD_NUMBER { get; set; }
        public string SKU_NUMBER { get; set; }
        public string CURE_NUMBER { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
    }
}
