//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_NOTIFICATION_LOG
    {
        public decimal NOTIFICATION_LOG_ID { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string DEPT { get; set; }
        public string MACHINE { get; set; }
        public string OPERATOR_BADGE { get; set; }
        public string CALL_TYPE { get; set; }
        public string SHIFT { get; set; }
        public string COMMENTS { get; set; }
        public string PRIORITY { get; set; }
        public string WORK_CENTER { get; set; }
        public string SYMPTOM { get; set; }
        public string FUNCTIONAL_LOCATION { get; set; }
    }
}
