//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIFT_DEFINITION
    {
        public decimal SHIFT_DEFINITION_ID { get; set; }
        public string DAY_OF_WEEK { get; set; }
        public string SHIFT { get; set; }
        public decimal START_HOUR { get; set; }
        public decimal START_MINUTE { get; set; }
        public decimal DURATION_IN_HOURS { get; set; }
        public string WORK_HOURS { get; set; }
    }
}
