//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnaDunlopBarcodeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPH_STANDARDS
    {
        public decimal ID { get; set; }
        public Nullable<decimal> DEPT { get; set; }
        public string AREA { get; set; }
        public string MACHINE_GROUP { get; set; }
        public Nullable<decimal> GTNCOMPONENT { get; set; }
        public Nullable<decimal> DAY_STD_HOURS_PER_UNIT { get; set; }
        public Nullable<decimal> DAY_UNITS_PER_HOUR { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_FROM { get; set; }
        public string EFFECTIVE_TILL { get; set; }
        public string TYPE { get; set; }
        public string COMPONENTS { get; set; }
        public Nullable<decimal> MUD_SECONDS { get; set; }
    }
}
