--------------------------------------------------------
--  DDL for Table PART_HISTORY
--------------------------------------------------------

  CREATE TABLE "ORACLE"."PART_HISTORY" 
   (	"PART_HISTORY_ID" NUMBER, 
	"PART_ID" NUMBER, 
	"SERIAL_NUMBER" VARCHAR2(15 BYTE), 
	"GOODYEAR_SERIAL_NUMBER" VARCHAR2(10 BYTE), 
	"GREEN_TIRE_NUMBER" VARCHAR2(5 BYTE), 
	"CREATED_ON" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PART_HISTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORACLE"."PART_HISTORY_PK" ON "ORACLE"."PART_HISTORY" ("PART_HISTORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PART_HISTORY_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORACLE"."PART_HISTORY_INDEX1" ON "ORACLE"."PART_HISTORY" ("SERIAL_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PART_HISTORY_INDEX2
--------------------------------------------------------

  CREATE INDEX "ORACLE"."PART_HISTORY_INDEX2" ON "ORACLE"."PART_HISTORY" ("GOODYEAR_SERIAL_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PART_HISTORY_INDEX3
--------------------------------------------------------

  CREATE INDEX "ORACLE"."PART_HISTORY_INDEX3" ON "ORACLE"."PART_HISTORY" ("GREEN_TIRE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PART_HISTORY
--------------------------------------------------------

  ALTER TABLE "ORACLE"."PART_HISTORY" ADD CONSTRAINT "PART_HISTORY_PK" PRIMARY KEY ("PART_HISTORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ORACLE"."PART_HISTORY" MODIFY ("PART_HISTORY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ORACLE"."PART_HISTORY" MODIFY ("PART_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ORACLE"."PART_HISTORY" MODIFY ("SERIAL_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "ORACLE"."PART_HISTORY" MODIFY ("GOODYEAR_SERIAL_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "ORACLE"."PART_HISTORY" MODIFY ("GREEN_TIRE_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "ORACLE"."PART_HISTORY" MODIFY ("CREATED_ON" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PART_HISTORY
--------------------------------------------------------

  ALTER TABLE "ORACLE"."PART_HISTORY" ADD CONSTRAINT "PART_HISTORY_PART_FK1" FOREIGN KEY ("PART_ID")
	  REFERENCES "ORACLE"."PART" ("PART_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger PART_HISTORY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ORACLE"."PART_HISTORY_TRG" BEFORE INSERT ON PART_HISTORY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.PART_HISTORY_ID IS NULL THEN
      SELECT PART_HISTORY_SEQ.NEXTVAL INTO :NEW.PART_HISTORY_ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ORACLE"."PART_HISTORY_TRG" ENABLE;
