--------------------------------------------------------
--  DDL for Table PART
--------------------------------------------------------

  CREATE TABLE "ORACLE"."PART" 
   (	"PART_ID" NUMBER, 
	"SERIAL_NUMBER" VARCHAR2(128 BYTE), 
	"GREEN_TIRE_NUMBER" VARCHAR2(50 BYTE), 
	"GOODYEAR_SERIAL_NUMBER" VARCHAR2(50 BYTE), 
	"CREATED" DATE DEFAULT sysdate
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PART_SERIAL_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORACLE"."PART_SERIAL_UK1" ON "ORACLE"."PART" ("SERIAL_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index Part_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORACLE"."Part_PK" ON "ORACLE"."PART" ("PART_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PART_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORACLE"."PART_INDEX1" ON "ORACLE"."PART" ("GOODYEAR_SERIAL_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PART
--------------------------------------------------------

  ALTER TABLE "ORACLE"."PART" ADD CONSTRAINT "PART_SERIAL_UK1" UNIQUE ("SERIAL_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ORACLE"."PART" ADD CONSTRAINT "Part_PK" PRIMARY KEY ("PART_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ORACLE"."PART" MODIFY ("PART_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ORACLE"."PART" MODIFY ("SERIAL_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "ORACLE"."PART" MODIFY ("CREATED" NOT NULL ENABLE);
